# Every published entry, in journal order
# The table of contents of the whole journal: citation label, title, date and
# types of each entry. An entry with several types appears once, its types
# joined with a slash.
#
# Squirrel Papers - https://squirrelpapers.github.io/sparql/
# Graphs: downloads/squirrelpapers.ttl, downloads/squirrelpapers.crm.ttl, vocab/types.ttl, ontology/index.ttl

PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX crmdig: <http://www.ics.forth.gr/isl/CRMdig/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX event: <http://purl.org/NET/c4dm/event.owl#>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sqp: <https://w3id.org/squirrelpapers/ontology#>
PREFIX sqpt: <https://w3id.org/squirrelpapers/type/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?label ?title ?issued (GROUP_CONCAT(?type; separator=" / ") AS ?types) ?entry
WHERE {
  ?entry a bibo:Document ;
         sqp:citationLabel ?label ;
         dct:title ?title ;
         dct:issued ?issued ;
         prism:volume ?volume ;
         prism:number ?issue ;
         sqp:entryNumber ?n .
  OPTIONAL { ?entry dct:type/skos:notation ?type }
  # Sort keys as plain integers: volume and issue are strings in PRISM.
  BIND(xsd:integer(?volume) AS ?v)
  BIND(xsd:integer(?issue) AS ?i)
  BIND(xsd:integer(?n) AS ?e)
}
GROUP BY ?label ?title ?issued ?entry ?v ?i ?e
ORDER BY ?v ?i ?e
